import type { Metadata } from 'next'
import {
  Inter,
  Roboto_Mono,
  Work_Sans,
  Montserrat_Alternates,
} from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const work_sans = Work_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-work-sans',
})
const montserrat_alternates = Montserrat_Alternates({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500'],
  variable: '--font-montserrat-alternates',
})
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${work_sans.variable} ${montserrat_alternates.variable} ${roboto_mono.variable}`}
    >
      <body className=" bg-mainBackgraound">{children}</body>
    </html>
  )
}
